name: Deploy Terraform

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Terraform
        uses: ./.github/actions/deploy
        with:
          environment: prod
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          s3-state-bucket: ${{ secrets.S3_STATE_BUCKET }}
          s3-state-key: ${{ secrets.S3_PROD_STATE_KEY }}
          terraform-version: "~> 1.5"
          auto-approve: "true"
